apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
    env: test
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
